name: Visiq AI Automation

on:
  workflow_dispatch:

  schedule:
    - cron: '0 1 * * *'
    - cron: '0 13 * * *'
    - cron: '0 17 * * *'
    - cron: '0 21 * * *'
jobs:
  generate-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: |
          python main.py

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: visiq-ai-output
          path: |
              topic.txt
              script.txt
              title.txt
              description.txt
              hashtags.txt
              scene_prompts.txt
              image_1.jpg
              image_2.jpg
              image_3.jpg
              image_4.jpg
              image_5.jpg
              image_6.jpg
              image_7.jpg
              image_8.jpg
              image_9.jpg
              image_10.jpg
              voice.mp3
              background.jpg
              thumbnail.jpg
              final_video.mp4
              
